### ISSUE TITLE
wiki de principios solid en poo

### ISSUE THREAD

**Issue by ayelenlscabral** [CodeSystem2022/Grupo_Programacion-UTN-CuartoSemestre#55]
SUBIR A LA WIKI INFORMACIÓN DE PROPIEDAD SOLID: PRINCIPIO ABIERTO Y CERRADO Y OTRO DE PRINCIPIO DE RESPONSABILIDAD ÚNICA.

**Comment by EduMaxiMontes** [comment]
Listo.
